### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by s-j-mc** [azizmithani/roast#1]
Hello,

I am interested in using roast, but have struggled to get it installed. I have tried setting up and running roast (environment setup with conda), but ran into a number of problems:

1. roast-complie.sh has a space between `-` and `lbamtools`
2. bySoftclip has an error (looks like no return inside the blocks?) :
```
bySoftclip.cpp: In member function ‘std::string bySoftclip::overlapmerge_left(std::string, std::string, int, int, int)’:
bySoftclip.cpp:1137:1: warning: control reaches end of non-void function [-Wreturn-type]
 1137 | }
      | ^
bySoftclip.cpp: In member function ‘std::string bySoftclip::overlapmerge_right(std::string, std::string, int, int, int)’:
bySoftclip.cpp:1152:1: warning: control reaches end of non-void function [-Wreturn-type]
 1152 | }
      | ^
```
3. cd-hit appears not to be installed:
```
Couldn't run cd-hit-est successfully, please check input reference file and path folder of external tools
   --cdHitEST                    For any library version issue ignore removing redundancy using CD-HIT-EST by setting it to 0, default 1
```

4. BAM files could not be opened `Could not open BAM file.` Admittedly this last one may be fixed by correcting steps 1-3 instead of the workarounds I implemented.

Thanks,
Sam

**Comment by Shabbirm21** [comment]
Hi Sam,

1. Thanks for pointing that out, it’s fixed now.

2. These warnings do not affect the performance/output of the tool, but I will look into that and will update accordingly.

3. cd-hit appears not to be installed: executable cd-hit is present in the external tools directory, however sometimes due to permission issues on a new machine or incompatibility with a different Linux version/flavor it is required to be installed and placed in the external tool folder accordingly. The version issue is also mentioned in the error message generated. 

4. That’s not an error or problem itself instead the outcome of any earlier failed step where the bam file couldn’t be generated at all/properly, which is mostly due to an installation error of the whole tool or in any external tool/library.

I hope that answer your queries, I am closing the issue now. Feel free to reopen if still there is any issue.

Best,
Madiha
